on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
   hello-world:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
       - name: generate test coverage
         run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
       - name: check test coverage
         uses: vladopajic/go-test-coverage@v2
       - run: go build -o main
