name: install go

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
   install-go:
     runs-on: ubuntu-latest
     steps:
       - uses: 'actions/checkout@v4'
       - uses: actions/setup-go@v5
       - run: go version
