name: Secret Scan

on: [pull_request]
permissions: 
  issues: write
  pull-requests: write

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for secrets using Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json_file_path: "sample_json_file.json"
      - run: echo ${{ steps.table.outputs.table }} >> gitleaks.md

      - name: Create GitHub Issue if secrets found
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Secret detected in code"
          content-filepath: ./gitleaks.md
          labels: |
            report
            automated issue
