name: Secret Scan

on: [pull_request, push, workflow_dispatch]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for secrets using Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-dir: .   
          verbose: true  
          redact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

